version: "3"
services:
  zookeeper:
    image: zookeeper:3.4.10
    network_mode: host
  mesos_master:
    image: mesosphere/mesos-master:1.2.0
    network_mode: host
    environment:
      MESOS_ZK: "zk://localhost:2181/mesos"
      MESOS_WORK_DIR: "/var/tmp/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_IP: 167.114.231.229
      MESOS_HOSTNAME: 167.114.231.229
    depends_on:
      - zookeeper
  mesos_agent:
    image: mesosphere/mesos-agent:1.2.0
    network_mode: host
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.pid:/var/run/docker.pid
      - /cgroup:/cgroup
      - /sys:/sys
      - /usr/bin/docker:/usr/bin/docker
      - ./go-mesos-executor:/usr/libexec/mesos/mesos-docker-executor
      - ./config.yaml:/etc/mesos-executor/config.yaml
      - /proc:/mnt/proc
    environment:
      MESOS_MASTER: "zk://localhost:2181/mesos"
      MESOS_WORK_DIR: "/var/tmp/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_CONTAINERIZERS: "docker,mesos"
    depends_on:
      - zookeeper
      - mesos_master
  marathon:
    image: mesosphere/marathon:v1.4.3
    network_mode: host
    environment:
      MARATHON_MASTER: "zk://localhost:2181/mesos"
      MARATHON_ZK: "zk://localhost:2181/marathon"
    depends_on:
      - zookeeper
      - mesos_master
