version: "3"
services:
  zookeeper:
    image: zookeeper:3.4.10
    network_mode: host
  mesos_master:
    image: mesosphere/mesos-master:1.3.1
    network_mode: host
    environment:
      MESOS_ZK: "zk://localhost:2181/mesos"
      MESOS_WORK_DIR: "/var/tmp/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_IP: 127.0.0.1
      MESOS_HOSTNAME: "localhost"
    depends_on:
      - zookeeper
  mesos_agent:
    image: mesosphere/mesos-slave:1.3.1
    network_mode: host
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.pid:/var/run/docker.pid
      - /cgroup:/cgroup
      - /sys:/sys
      - ./go-mesos-executor:/usr/libexec/mesos/mesos-docker-executor
      - ./config.yaml:/etc/mesos-executor/config.yaml
      - /proc:/mnt/proc
    environment:
      MESOS_MASTER: "zk://localhost:2181/mesos"
      MESOS_WORK_DIR: "/var/tmp/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_CONTAINERIZERS: "docker,mesos"
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
    depends_on:
      - zookeeper
      - mesos_master
  marathon:
    image: mesosphere/marathon:v1.4.3
    network_mode: host
    environment:
      MARATHON_MASTER: "zk://localhost:2181/mesos"
      MARATHON_ZK: "zk://localhost:2181/marathon"
    depends_on:
      - zookeeper
      - mesos_master
